# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  #- osx
  
julia:
  - 1.3
  - nightly
  
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
  
notifications:
  email: false
  
git:
  depth: 99999999
  
matrix:
  allow_failures:
  - julia: nightly
  - os: osx

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("BHAPtFEM"); Pkg.test("BHAPtFEM"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("BHAPtFEM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
